//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::Model_Viewer_3d::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct DirectXPageT : public ::winrt::Model_Viewer_3d::implementation::DirectXPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename DirectXPageT::base_type;
        using base_type::base_type;
        using class_type = typename DirectXPageT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::SwapChainPanel swapChainPanel()
        {
            return _swapChainPanel;
        }
        void swapChainPanel(::winrt::Windows::UI::Xaml::Controls::SwapChainPanel value)
        {
            _swapChainPanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBar bottomAppBar()
        {
            return _bottomAppBar;
        }
        void bottomAppBar(::winrt::Windows::UI::Xaml::Controls::AppBar value)
        {
            _bottomAppBar = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct DirectXPage_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::SwapChainPanel _swapChainPanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBar _bottomAppBar{nullptr};
    };
}

